const {
  AllAppUsersModel,
  custom_menu_links_locations,
  chatAppUsersModel,
  chatAppLocationsModel,
  HideAppLocationsModel,
  TransactionAppLocationsModel,
  SnapshotOnboardingLocationsModel,
  CalendersMapLocationsModel,
  AgencyTaskUsersModel,
  AgencyTaskLocationsModel,
  LimitedAppLocationsModel,
  AllAppLocationsModel,
  LocDashLocationsModel,
  CalenderWidgetLocationsModel,
  JobNimbusLocationsModel,
  AcculynxLocationsModel,
  CustomizerLocationsModel,
  locationHeadquarterLocs,
  LevelUpLocationsModel,
  AppCreatorLocationsModel,
} = require("../model");

const collections = {
  chatAppLocations: chatAppLocationsModel,
  chatAppUsers: chatAppUsersModel,
  hideAppLocations: HideAppLocationsModel,
  TransactionAppLocations: TransactionAppLocationsModel,
  SnapshotOnboardingLocations: SnapshotOnboardingLocationsModel,
  CalendersMapLocations: CalendersMapLocationsModel,
  AgencyTaskUsers: AgencyTaskUsersModel,
  AgencyTaskLocations: AgencyTaskLocationsModel,
  LimitedAppLocations: LimitedAppLocationsModel,
  LocDashLocations: LocDashLocationsModel,
  CalenderWidgetLocations: CalenderWidgetLocationsModel,
  JobNimbusLocations: JobNimbusLocationsModel,
  AcculynxLocations: AcculynxLocationsModel,
  CustomizerLocations: CustomizerLocationsModel,
  locationHeadquarterLocs: locationHeadquarterLocs,
  custom_menu_links_locations: custom_menu_links_locations,
  AllAppLocations: AllAppLocationsModel,
  AllAppUsersModel: AllAppUsersModel,
  LevelUpLocations: LevelUpLocationsModel,
  AppCreatorLocations: AppCreatorLocationsModel,
};
const auth_data_collections = {
  JobNimbusLocations: JobNimbusLocationsModel,
  AcculynxLocations: AcculynxLocationsModel,
  CalenderWidgetLocations: CalenderWidgetLocationsModel,
  LocDashLocations: LocDashLocationsModel,
  TransactionAppLocations: TransactionAppLocationsModel,
  AppCreatorLocations: AppCreatorLocationsModel,
};
module.exports = {
  collections,
  auth_data_collections,
};
